### PR TITLE
Fixed a minor bug that copy action is enabled even though a trigger button is disabled.

### PR DESCRIPTION
**Pull request by ogaoga**
Inserted a small logic to check if the target is disabled in order to avoid flashing the target textarea when the disabled button is clicked.

### CODE REVIEW

**Comment by kafeltz** [comment]
Is this code reached? I think disabled elements can't even be click to trigger the event.

**Comment by ogaoga** [comment]
I could reproduced the issue on CodePen.
http://codepen.io/ogaoga/pen/yJNgZG

But I found it occurs only when you click a target button using Material Icon.

So this issue is not due to Clipboard.js but it would be good for using like Material Icon.

**Comment by zenorocha** [comment]
This is probably an issue on [good-listener](https://github.com/zenorocha/good-listener). Semantically speaking `disabled` elements are not supposed to work, `readonly` is the proper attribute to use.

**Comment by zenorocha** [comment]
Thanks for contributing @ogaoga!

**Pull request closed without merging**
