### PR TITLE
Use a div for the fake element to support HTML text

### PR DESCRIPTION
**Pull request by jimryan**
This PR replaces the `textarea` element that's created when the text property is set with a `div` to support HTML text.

I needed to copy off-screen text with some HTML in it (to bold certain text), but didn't see any officially supported way to accomplish that with clipboard.js, short of creating my own off-screen div and using that as the target element.  I was about to do that, when I wondered if clipboard.js should just use a `div` all of the time, so I tested it a bit, and have found broad browser support and no downsides.

This has been tested on Chrome 72, Safari 12, Firefox 65, Mobile Safari (iOS 12.1), and IE 11 (Windows 7).

I don't claim to be an expert on cross-browser clipboard interaction, so if textareas are better suited for this, or more widely supported, please let me know.  If that's the case, perhaps we could find another way for the library to support HTML text via the data attribute.  

With this PR, the following works:

```
<button class="btn" data-clipboard-text="Just because you can <strong>doesn't</strong> mean you should — clipboard.js">
    Copy to clipboard
</button>
```

When pasted somewhere that supports HTML text on the clipboard (e.g. Word):
> Just because you can **doesn't** mean you _should_ — clipboard.js

When pasted elsewhere (e.g. here, in Github's textarea):
> Just because you can doesn't mean you should — clipboard.js

Thanks for the awesome library!

### CODE REVIEW

**Comment by zenorocha** [comment]
I remember trying to use textarea, but there are side effects to this like losing styling properties that browsers copy when using a div.

In any case, thanks for the PR!

**Comment by jimryan** [comment]
@zenorocha thx for taking a look at this. I’m not sure I understand the issue with a `div` over a `textarea`, but if there are issues, would you be open to a PR that makes the underlying element optional? That way the default `textarea` remains but the user can opt to use a `div` to support HTML. 

I’ve been using this PR in a production application since opening it with great success and would love to get this merged in some way as it solves a real problem and materially improved the library for this use-case (copying off-screen text with HTML).

**Comment by jimryan** [comment]
Hey @zenorocha! Hope you're well. 

We're still using this in a production application with success and it solves a very important need for us: It allows us to copy off-screen HTML.

I hear you on the potential pitfalls swapping out the textarea for a div across the board, but would you be open to a PR that adds a _new_ option that uses a div? Something like `data-clipboard-html` or such? That gives the user a path to copying HTML text without using their own element, which is currently not supported by the library.

**Comment by jimryan** [comment]
Hey @zenorocha! Hope you're well. 

We're still using this in a production application with success and it solves a very important need for us: It allows us to copy off-screen HTML.

Re-reading your original reply, I think you may have misunderstood what this PR does. The library _currently_ uses a `textarea` and this PR replaces it with a `div` for the exact reason you specified - to copy HTML content.

Still, I understand there may be potential pitfalls in swapping out the `textarea` for a `div` across the board, and perhaps the `textarea` was used for a reason originally, so would you be open to a PR that adds a _new_ option that uses a `div`? Something like `data-clipboard-html` or such? That gives the user a path to copying HTML text without using their own element, which is currently not supported by the library.

**Pull request closed without merging**
