### PR TITLE
Switch bundling to use rollup

### PR DESCRIPTION
**Pull request by realityking**
This is an alternative to #541

The main advantage is a vastly smaller bundle (minified version is 1.5 kB or 15% smaller) but using rollup will also make it easier to ship CommonJS and ESM versions of Clipboard.js.

The main reasons why the build is smaller are:
- All modules inlined together, removing a lot of overheard
- Babel helpers are only included once
- Individual modules are not converted to UMD modules before bundling

### CODE REVIEW

**Comment by jpike88** [comment]
One month later, nothing.

@zenorocha appreciate some sort of comment here

**Comment by zenorocha** [comment]
Sorry, at this moment I don't have the time to review it.

**Comment by veeramarni** [comment]
@realityking Thanks for the PR. I believe we need to apply this PR quickly as the `clipboard` started failed with following errors when using latest `webpack@4.19.01` in our project. 
image


@zenorocha Please share your thoughts on this. If you do need time then we plan to create a temporary package until it is official from you.

**Comment by jpike88** [comment]
@zenorocha if y I don’t have the time to review PR, it’s probably a good idea to grant someone’s else the ability to do so

**Comment by jpike88** [comment]
@veeramarni if nothing gets done let me know what npm package you're calling it, I'll just switch to that

**Comment by veeramarni** [comment]
If anyone needs it quickly, here is the package I have created. 

cdm-clipboard@2.0.1

**Comment by zenorocha** [comment]
Hey guys, sorry for the delay. I really appreciate your effort.

I decided to migrate to Webpack 4 instead since it's a tool that has been more adopted by the community. Please try the new version `2.0.2` and let me know if it's working for you.

Thanks!

**Pull request closed without merging**
