### PR TITLE
Create composer.json for instalation with composer

### PR DESCRIPTION
**Pull request by alphp**
The installation is much simpler with Composer and https://github.com/RobLoach/component-installer

After merged you can test it:
```
composer config repositories.zenorocha-clipboardjs vcs "https://github.com/zenorocha/clipboard.js/"
composer require zenorocha/clipboardjs:dev-master
```
Before merged you can test using my git fork.

Composer creates a "components" folder that contains the "clipboardjs" whith all files spec in "files" of composer.json.
You can then register the "package" at https://packagist.org In this way the installation would be simpler:
`composer require zenorocha/clipboardjs:dev-master`

### CODE REVIEW

**Comment by Ruffio** [comment]
@zenorocha  is there anything holding this PR back?

**Comment by alphp** [comment]
If you do not work with composer this PR does not add anything.
If you use composer to have the dependencies of your project updated this PR will be of great help.

**Comment by Ruffio** [comment]
@zenorocha is there anything holding this PR back?

**Comment by zenorocha** [comment]
Anything holding it back, I just wasn't able to properly test it.

**Pull request merged**
