### PR TITLE
Added destroy lifecycle method

### PR DESCRIPTION
**Pull request by kmalakoff**
With single page apps, you may want to manage the lifecycle of the DOM more precisely. I have added a pull request for a destroy method that can be used to clean up the events when pages change.

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @kmalakoff, that would be a good addition. 

Here are some things that could be improved:
* According to [delegate-events](https://www.npmjs.com/package/delegate-events) docs, the 3rd param is a callback so we don't need that when unbinding.
* Destroy method should be added on `ClipboardAction` too and `Clipboard` should call it.

**Comment by kmalakoff** [comment]
All of those sound good assuming one instance of Clipboard is managed as a group.

FYI: I originally tried to use ClipboardAction directly (understanding the event delegation tradeoff) given https://github.com/zenorocha/clipboard.js/issues/25 since it wold be easier to integrate with React so definitely a destroy on the ClipboardAction could be good to expose a lower-level API. That said, after multiple attempts, I couldn't get it to work so settled with the jQuery approach using Clipboard.

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Thank you, pull request merged! <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Merged, tested and documented. Would you mind checking the final result and leave your opinions? Thanks for contributing @kmalakoff.

**Comment by kmalakoff** [comment]
Yeah, works well. Thanks!

**Pull request closed without merging**
