### PR TITLE
Document the browser restriction for a valid element

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
Related to #127.

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @FagnerMartinsBrack, thanks for sending this PR.

I think we should create a wiki page like we're doing with [Known Issues](https://github.com/zenorocha/clipboard.js/wiki/Known-Issues).

**Comment by zenorocha** [comment]
Here's a new [Known Limitations](https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations) page, feel free to collaborate there.

**Comment by FagnerMartinsBrack** [comment]
You will probably see in your "Traffic" page that the "Wiki" has very few access. It would be worth linking the wiki somewhere in the README.md in order to make it clear that the Wiki is actually being used in this project, by default the assumption seems to be that nobody goes in the Wiki menu unless there is an evidence that it is being used for something.

In other hand I really believe that abstractions should be documented along with the API, you should not infer previous knowledge of the API internals in the public API because that causes abstractions to leak through the code and return unexpected results. Of course, sometimes it is not feasible to document every single assumption in the first version, but one or more bug reports are evidence that the abstraction is leaking for early adopters and therefore it make sense documenting in the public API.

**Comment by FagnerMartinsBrack** [comment]
https://github.com/zenorocha/clipboard.js/wiki/Known-Limitations/267284196e99747efdf6cd3e9972cfcf1eafe9c5

**Comment by zenorocha** [comment]
I've been rethinking docs and will add a link to Wiki at some point.

**Pull request closed without merging**
