### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by plesiecki**
Correct module path

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @plesiecki,

Thanks for sending this pull request. Can you provide more information about why this is needed?

**Comment by plesiecki** [comment]
Sure, I bundle using Rollup, looks like rollup reads `module` field from package.json and I got `Unresolved dependencies` error because `src/` is "npmignored".

**Comment by Ruffio** [comment]
@zenorocha should this PR be merged?

**Comment by zenorocha** [comment]
Thanks @plesiecki!

**Comment by realityking** [comment]
I don't understand this PR. `dist/clipboard.js` is not an ESM module, why is it listed in the `module` field?

**Pull request merged**
