### PR TITLE
Do not clear text on mobile devices - fix #26

### LINKED ISSUE #26: Add support for text selection on mobile

### PR DESCRIPTION
**Pull request by mdibaiee**
I also added an option to forcefully clear the input, in case someone doesn't want this to happen while calling `clearSelection` in their event listeners.

Tested on my Firefox for Android, seems to work well.

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @mdibaiee,

A developer should what have the ability to clear a selection or not, regardless of platform. This kind of checking should be done in your success callback.

**Comment by zenorocha** [comment]
Thanks for your contribution anyways ;)

**Comment by mdibaiee** [comment]
I think you don't want me to continue working on this, as you closed the Pull request and give me this:

> Thanks for your contribution anyways ;)

It doesn't bother me much, but please be more polite to the community. You're doing it wrong.

**Comment by zenorocha** [comment]
Not every PR get merged @mdibaiee, you shouldn't feel offended by that. As I explained above, a developer should have control over selection, regardless of platform. That's why we expose the clearSelection function.

**Comment by mdibaiee** [comment]
@zenorocha I know, I'm an active open-source contributor, there are two cases with a PR, you either close it as you "dont want it at all", or you ask the contributor to modify the patch to fit your needs, I've been through this kind of things a lot, the maintainer says he wants something, after you make a PR, he changes his mind.

Contributors are not work-less, life-less people with cheap time.

**Pull request closed without merging**
