### PR TITLE
Feature Prettier

### PR DESCRIPTION
**Pull request by vitormalencar**
## Description
This PR adds Prettier to be our code style formatting tool

## Motivation and Context
with more collaborators now, we want to improve the development experience while maintaining a unique code style consistent with the project.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Refactor (non-breaking change which is refactoring/cleaning existing functionality)
- [ ] Breaking change (which would cause existing functionality to change)

### CODE REVIEW

**Review by obetomuniz — APPROVED** [review]
LGTM. Just solve the conflicts and ensure the tests passing before merge.

**Review by helderburato — APPROVED** [review]

**Comment by helderburato** [comment]
Considering this updated https://github.com/zenorocha/clipboard.js/pull/720#pullrequestreview-572433693 to set single quotes to merge the PR.

**Review by helderburato — CHANGES_REQUESTED** [review]
Need to set "single quote" as standard.

**Review by helderburato — APPROVED** [review]
Great job! 🤘

**Pull request merged**
