### PR TITLE
fix: change export from commonjs to es module for import from src usage.

### PR DESCRIPTION
**Pull request by LeuisKen**

### CODE REVIEW

**Comment by zenorocha** [comment]
Thanks @LeuisKen.

When I run `npm run build` and try one of the examples from `demo` folder, it doesn't seem to work properly.

**Comment by zenorocha** [comment]
@realityking would you mind taking a look? I would love a second opinion on this and I can see from your pull requests that you know that part pretty well ;)

**Comment by realityking** [comment]
This isn't working because babel is transforming the ESM to CommonJS before Webpack get its hands on it. See this line in my rollup PR for the fix: https://github.com/zenorocha/clipboard.js/pull/552/files#diff-e56633f72ecc521128b3db6586074d2cR9

**Comment by LeuisKen** [comment]
@realityking It take times for me to realize that we are focus on different issues, and now I understand what you really means. I have change my commits as your suggested. Thanks 😄

**Comment by Ruffio** [comment]
X-Ref to other PR, that covers some of the same: https://github.com/zenorocha/clipboard.js/pull/637

**Comment by ogonkov** [comment]
I think i will close my PR, because this PR looks better

**Comment by ogonkov** [comment]
@zenorocha can you look at this PR once more? Demos should look

**Comment by zenorocha** [comment]
I can confirm that demos are working now. Thanks everyone for your patience. I'll be releasing a new patch version soon.

**Pull request merged**
