### PR TITLE
Add Promise support

### PR DESCRIPTION
**Pull request by DSergiu**
**Use case:**
`On btn triger, an async operation is performed and the result must be copied.`

```
var clipboard = new ClipboardJS('.btn', {
     text: function() {
         return new Promise((resolve) => {
             setTimeout(() => {
                 resolve('to be or not to be after 1 second');
             }, 1000);
         });
     }
});
```

Would require changing description to:
✂️ Modern copy to clipboard. No Flash. Just **5kb** gzipped 📋

### CODE REVIEW

**Comment by DSergiu** [comment]
Nvm, no guarantee to succeed.

**Comment by cincodenada** [comment]
Why was this closed? Is there further work needed? I am looking for the ability to asynchronously set the text, I want to get the content to be copied from a database, so I don't want to make the call unless the copy button is clicked.

**Comment by joker-777** [comment]
Hi, we also would need this feature.

**Comment by joker-777** [comment]
@DSergiu ?

**Pull request closed without merging**
