### PR TITLE
Update the `Browser Support` section

### PR DESCRIPTION
**Pull request by alrra**
* Update the `Chrome` and `Opera` logos.
* Add `Edge` in the `Browser Support` section.

--

How the `Browser Support` section will looks at different breakpoints: [`1`](https://cloud.githubusercontent.com/assets/1223565/16239820/4b7400c2-37ef-11e6-8cd5-dc76e78db6da.png), [`2`](https://cloud.githubusercontent.com/assets/1223565/16239819/4b6ec04e-37ef-11e6-8210-39b9114a990f.png) and [`3`](https://cloud.githubusercontent.com/assets/1223565/16239821/4b78cb84-37ef-11e6-99c0-f8bac376c2bc.png).

### CODE REVIEW

**Comment by zenorocha** [comment]
Awesome! Would you mind updating the README as well?

**Comment by zenorocha** [comment]
If it works on IE9 I think people assume that Edge is also supported. I guess we can remove that icon

**Comment by alrra** [comment]
> Awesome! Would you mind updating the README as well?

Done in https://github.com/zenorocha/clipboard.js/pull/268 (since the `readme.md` is in `master` branch)

**Comment by alrra** [comment]
From https://github.com/zenorocha/clipboard.js/pull/268#issuecomment-227522630

>  Also if it's supported on IE9 I think people would assume that it's supported on Edge as well.

I disagree with that, but updated my PR to remove the related commit :)

**Comment by zenorocha** [comment]
Thanks!!

**Comment by molant** [comment]
@zenoracha Edge is not IE. Perpetuating that notion will only confuse developers and users.
One could argue that Opera is closer to Chrome than Edge is to IE but you still make a difference between those 2 browsers. Why not do the same with Edge?

Virtually any support matrix out there makes a distinction between IE and Edge (https://kangax.github.io/compat-table/es6/, http://html5accessibility.com/, http://caniuse.com/, http://html5test.com/ just to name a few).

**Comment by zenorocha** [comment]
Ok, let's do this. Could you send a PR?

**Comment by molant** [comment]
Sure, thanks!

**Comment by molant** [comment]
Something like this for gh-pages
image

Or want something different, other order?

Also unless I'm mistaken I should be doing 2 PRs. One for gh-pages and the other to update the readme.md, right?

**Comment by molant** [comment]
Although I can let @alrra just submit his original code and that will be easier...

**Comment by alrra** [comment]
> I can let @alrra just submit his original code and that will be easier...

Done in #315 and #316.

**Comment by zenorocha** [comment]
Thanks @molant for making an argument about this and @alrra for implementing it :)

https://github.com/zenorocha/clipboard.js#browser-support
https://clipboardjs.com/

**Pull request merged**
