### PR TITLE
Using template strings

### PR DESCRIPTION
**Pull request by jaydson**
- Using template strings to interpolation
- Less code, assigning an `attr` variable instead of repetition

Tests are passing.
I kept the dist folder (as mentioned before for bower purposes)

### CODE REVIEW

**Comment by lipis** [comment]
You should install a plugin for http://editorconfig.org in your editor.. to avoid the trailing spaces and final new line :) 
https://github.com/zenorocha/clipboard.js/blob/master/.editorconfig

**Comment by zenorocha** [comment]
Closing this one in favor of #63

**Comment by zenorocha** [comment]
Thanks for contributing @jaydson!

**Comment by jaydson** [comment]
:+1:

**Comment by zenorocha** [comment]
Ended up using template string though :P https://github.com/zenorocha/clipboard.js/commit/c16137511c8a1769effc9d58f067cd4e407a8800#diff-2db77e7b10eb10844f23dd960369d74aR94

**Comment by jaydson** [comment]
Aaha cool!

**Pull request closed without merging**
