### PR TITLE
Elements support

### LINKED ISSUE #25: Idea: pass in the elements
With single page apps, you may want to manage the lifecycle of the DOM more precisely. 

What I would like would be for a way to provide a single element or list of elements that are used instead of having the library use the selector to find elements on the document. Otherwise, it feels like jQuery spaghetti by adding extra classes to HTML (FYI: I'm using React refs to find elements).

### PR DESCRIPTION
**Pull request by arve0**
Removed `component-event` from #42. Fixes #25.

### CODE REVIEW

**Comment by arve0** [comment]
I've removed `delegate-events` and use `addEventListener` (along with `querySelector`) instead. Please revise.

**Comment by cinaglia** [comment]
@zenorocha might have more input on this, but I'm pretty sure event delegation was used for performance reasons, as well as to take advantage of supporting multiple elements matching a given selector.

IMO, we should stick to using event delegation. Also, I believe Zeno has expressed his intent to support a list of nodes. An idea is to roll out a custom algorithm along the lines of:
* If selector is a string, [find the closest element matching it](https://github.com/HenrikJoreteg/delegate/blob/master/index.js#L30-L32) and use it.
* If selector is a single element and `e.target === selector`, use it.
* If selector is a NodeList and it contains `e.target`, use it.

We can then call `this.onClick()` with the appropriate element.

**Comment by arve0** [comment]
Aha! Thanks for the input. I'll see if I can make that work.

**Comment by aleksanb** [comment]
Looking forward to a feature like this in the soon-to-come future!

**Comment by zenorocha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by zenorocha** [comment]
Hey guys, sorry for taking so much to merge this.

I wanted to sure we had a pretty versatile and robust solution, but I realized it was too much code to put it here. So I ended up creating a new module called [good-listener](https://github.com/zenorocha/good-listener). https://github.com/zenorocha/clipboard.js/commit/6b1f6b22a65a0751a5e2ab04504f06c14673c4b4

This module does exactly what @cinaglia described above and I'd love to hear your feedback on it.

---

Thanks so much @hasansoydabas and @arve0 for pushing feature.

**Comment by FagnerMartinsBrack** [comment]
> So I ended up creating a new module called good-listener. 6b1f6b2

A few years from now the only thing that will be remembered is that:

"In the beginning there was this singularity that started everything"
-- The jQuery Bang Theory

**Pull request closed without merging**
