### PR TITLE
Remove unnecessary code and add node version control

### PR DESCRIPTION
**Pull request by obetomuniz**
This PR remove `import listen from 'good-listener'` dependency from `test/clipboard.js` and add `.nvmrc` to the project to control which Node version we will be using while running the project.

### CODE REVIEW

**Review by vitormalencar — APPROVED** [review]
Nice work 🚀  simple and clean

**Review by helderburato — APPROVED** [review]
Great job! 🤘

**Review by zenorocha — CHANGES_REQUESTED** [review]
The rest of the code base is single quote `'`, I think it's better to keep it standardized

**Comment by vitormalencar** [comment]
@zenorocha the other PR adds prettier putting double quotes as the default, 
we can also change there if needed

**Comment by obetomuniz** [comment]
Sure! Let's stay this PR on hold until get #721 merged.

**Pull request merged**
