### PR TITLE
Emit original event

### PR DESCRIPTION
**Pull request by pedroabreu**
Passing original event as an emitter option. This way we can handle the event on our side and stopPropagation ( for example ).

Same goal as https://github.com/zenorocha/clipboard.js/pull/475 but I think it's a more broad solution since we can handle the event the way we want.

Open to suggestions, ofc

### CODE REVIEW

**Comment by pedroabreu** [comment]
@zenorocha any thoughts on this ?

**Comment by pedroabreu** [comment]
@zenorocha thoughts on this ?

**Comment by wzalazar** [comment]
what is the status? I need the same feature¡, here +1

**Comment by Ruffio** [comment]
@zenorocha thoughts on this ?
Can it be merged?

**Comment by Ruffio** [comment]
@zenorocha thoughts on this ?

**Pull request closed without merging**
