### PR TITLE
Migrate from Browserify to Webpack

### LINKED ISSUE #371: Migrate from Browserify to Webpack

### PR DESCRIPTION
**Pull request by guillaumevincent**
close #371

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @guillaumevincent!

Thanks a lot for your pull request. Can you remove the `dist` changes so we don't have conflicts?

**Comment by guillaumevincent** [comment]
sure :)

**Comment by zenorocha** [comment]
Hey @guillaumevincent,

Thanks a lot for sending this pull request. I noticed that the banner wasn't added. Could you please add it and send another PR? Thanks!

**Comment by guillaumevincent** [comment]
@zenorocha the banner?

**Comment by zenorocha** [comment]
Yes, this thing over here:
* https://github.com/zenorocha/clipboard.js/blob/master/.banner
* https://github.com/zenorocha/clipboard.js/blob/master/dist/clipboard.min.js#L1-L6

**Comment by zenorocha** [comment]
Can you revisit this @guillaumevincent?

**Comment by zenorocha** [comment]
Finally merged, thanks @guillaumevincent!

**Pull request merged**
