### PR TITLE
Update clipboard.js

### PR DESCRIPTION
**Pull request by andersonbernardo**
e.preventDefault() to bind anchor

### CODE REVIEW

**Comment by kafeltz** [comment]
+692 −691  Diff just to add a simple line?

What if someone don't want this behavior or is not an anchor?

**Comment by zenorocha** [comment]
Hey @andersonbernardo, you made a change to the distribution file which is auto generated. Next time you want to send a PR edit the `src` folder.

**Comment by zenorocha** [comment]
Apart from that, you should use a button instead of an anchor on your side.

**Comment by kafeltz** [comment]
I didn't test, but <a href="javascript:void(0)"> will work. Sometimes, <a> is better than <button> in cases you like a tooltip over a "disabled" button. With buttons you need to wrap it. Anyway, it is easy to workaround this issue.

**Comment by zenorocha** [comment]
Anchors are semantically incorrect, regardless of disabled or readonly states.

**Comment by andersonbernardo** [comment]
Sorry!
I talked to my front end, he said that use anchors because in older browsers can not stylize button. but i agree are semantically incorrect, I will look for another alternative.

**Comment by kafeltz** [comment]
I think old browsers would not even work copy/paste javascript feature. So, the case is solved.

**Pull request closed without merging**
