### PR TITLE
Create before handler to choose if action will be executed or not

### LINKED ISSUE #366: "Copied!" magic!
Could someone help me to understand how I can make the magic with message shows "Copied!". It comes from aria-label attribute, but how I can set it? And then show it to user.

### PR DESCRIPTION
**Pull request by rafaelverger**
Closes https://github.com/zenorocha/clipboard.js/issues/336

### CODE REVIEW

**Comment by tupy** [comment]
+1

**Comment by guillaumevincent** [comment]
Promise will not be available on IE 9+ without a polyfill

**Comment by zenorocha** [comment]
Yep, I'm aware of that.

**Comment by guillaumevincent** [comment]
@zenorocha can I help you with something to accelerate promise support in clipboard.js ?

**Comment by guillaumevincent** [comment]
I not sure if this patch work on Firefox because document.execCommand('copy') doesn't work asynchronously 
see http://hansifer.com/clipboardCopyTest.html

**Comment by zenorocha** [comment]
Interesting @guillaumevincent, is this list up to date? Because iOS supports execCommand nowadays.

**Comment by guillaumevincent** [comment]
@zenorocha not sure but here simple test :

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Test</title>
</head>
<body>
<button onclick="copy(genPwd)">copy</button>
<script>
    function genPwd() {
        return new Promise(function(resolve) {
            resolve('toto')
        })
    }

    function copy(p) {
        p().then(function(result) {
            console.log('create fake text area');
            var fakeTextArea = document.createElement('textarea');
            fakeTextArea.setAttribute('readonly', '');
            fakeTextArea.value = result;
            document.body.appendChild(fakeTextArea);
            fakeTextArea.select();
            document.execCommand('copy');
        });
    }
</script>
</body>
</html>
```

It works on Chrome but not on Firefox

**Comment by zenorocha** [comment]
Ohh I see, looks like the idea of having a promise-based interface is no longer valid.

**Comment by guillaumevincent** [comment]
Or maybe with 17,325 ⭐️ we can make some noise and force Mozilla to allow clipboard async copy 1s! :D

**Comment by zenorocha** [comment]
hehehe that's true.

**Comment by zenorocha** [comment]
Closing this pull request since it doesn't work on Firefox as reported by @guillaumevincent. But thanks a lot for your contribution @rafaelverger.

**Pull request closed without merging**
