### PR TITLE
Add `modifier` key option

### PR DESCRIPTION
**Pull request by vekat**
An attempt to specify/customize the event trigger, suggested in #109.

The `modifier` option allows the Clipboard API to prevent the creation
of a new instance of `ClipboardAction` if the `click` event object is
not fired with a special key pressed.

It basically functions as a new type of event. The keys 'ctrl',
'shift', 'alt' and 'meta' are supported.

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @vekat, that's a good ideia but there's still lots of use cases not covered. What about double clicks #112? What about a combination of key strokes? I think we need to provide a way for people to specify their own event triggers.

**Comment by vekat** [comment]
I thought about it when I read issue #112.
I could add an option to use [dblclick](https://developer.mozilla.org/en/docs/Web/Events/dblclick) instead.

**Comment by vekat** [comment]
By the way @zenorocha, do you know why the Travis build failed?

**Comment by zenorocha** [comment]
My point is, I don't this should be built-in, it could be something they define on the constructor like https://github.com/zenorocha/clipboard.js#advanced-options

**Comment by zenorocha** [comment]
About the broken build that's probably because we don't list chai and phantomjs as devDependencies

**Comment by vekat** [comment]
Oh, ok I understand.
Then basically the user would need some control over the listener and the `onClick` method.
Do you already have a solution in mind?

**Comment by zenorocha** [comment]
I don't have a solution for it right now but maybe we could do something similar to the rest of the API.

1. `data-clipboard-event` attribute, could be used for simple stuff like dblclick
2. `event` function defined on the constructor that lets you add modifiers or whatever implementation you need

The thing is, it needs to be flexible and work on other platforms too, not only desktop.

**Pull request closed without merging**
