### PR TITLE
Supply a simple `#copy` api on plain text

### PR DESCRIPTION
**Pull request by danielravina**
Hi,

I used clipboard.js In two recent projects which in both, I needed to copy some text to the clipboard without having a button or a trigger. 

For example, there's a list of items where users can use the keyboard to navigate up and down, and on pressing 'Enter', the text in the item should be copied to the clipboard. I couldn't find a way to do it with the current API (which requires a DOM element to be clicked on) so I dug into the code and looked for ways to do it. Luckily, the code is very clean and well written so it was easy to implement such behavior

Here's the gist of what you can do now:
```js
// no arguments needed on initialization
let clipboard = new Clipboard() 

// callbacks still work as expected
clipboard.on('success', () => {
  console.log('Copied!')
})

// Simple API to copy text on the fly
clipboard.copy('hello world')
```

It might not be aligned with the philosophy of clipboard.js, but I think it's simple enough and expands the flexibility quite a lot!

### CODE REVIEW

**Comment by danielravina** [comment]
oh just found out there's already a PR for that! https://github.com/zenorocha/clipboard.js/pull/474
Guess I'm not the only one who needed this feature.

**Comment by zenorocha** [comment]
Hey @danielravina, I added a proposal for this feature. Can you check #518?

**Comment by Ruffio** [comment]
@danielravina what you say?

**Comment by danielravina** [comment]
Looks good to me! I 👍 it!

**Comment by Ruffio** [comment]
What is the status of this issue? Is it continued in #518 ?

**Comment by danielravina** [comment]
can close it for favour of #518

**Pull request closed without merging**
