### PR TITLE
Using contenteditable div instead of text area

### PR DESCRIPTION
**Pull request by petabyte**
Use contenteditable div to retain formatting
clipboard action container option should have the css styling in scope to return formatting
otherwise need the container to be document.body

### CODE REVIEW

**Comment by Pruus** [comment]
I would also like te use a <DIV> so the user can’t change only copy. My source sample:

Code php, list of images, show name and button

Echo ‘<div style="font-weight: bold; color: red"  id="B-'.$aantal.'">'.$target.$file.'<button class="btn" data-clipboard-action="copy" data-clipboard-target="#B-'.$aantal.'">&larr; Kopieer de link</button>'

How can i manage that with your code?

**Comment by petabyte** [comment]
@Ruffio https://html.spec.whatwg.org/multipage/interaction.html#contenteditable

**Comment by petabyte** [comment]
Looks like it is supported in most major browsers - and part the HTML LS  spec.

**Comment by petabyte** [comment]
Or just include an option to to use the editable div if users wants to retain the formatting - which fallbacks to the textarea if content editable is not supported in the browser.

**Comment by Ruffio** [comment]
What is the advantage if using div contenteditable compared to textarea?

**Comment by amccloud** [comment]
@Ruffio I think it copies any styling + images? See: http://owaisafaq.com/blog/demos/copier/

**Comment by zenorocha** [comment]
I tried the demo above but it doesn't seem to work in all browsers.

**Pull request closed without merging**
